config/routes.rb
Ss::Application.routes.draw do
  resources :looks

end

app/models/look.rb
class Look < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/looks_controller.rb
class LooksController < ApplicationController
  # GET /looks
  # GET /looks.json
  def index
    @looks = Look.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @looks }
    end
  end

  # GET /looks/1
  # GET /looks/1.json
  def show
    @look = Look.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @look }
    end
  end

  # GET /looks/new
  # GET /looks/new.json
  def new
    @look = Look.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @look }
    end
  end

  # GET /looks/1/edit
  def edit
    @look = Look.find(params[:id])
  end

  # POST /looks
  # POST /looks.json
  def create
    @look = Look.new(params[:look])

    respond_to do |format|
      if @look.save
        format.html { redirect_to @look, notice: 'Look was successfully created.' }
        format.json { render json: @look, status: :created, location: @look }
      else
        format.html { render action: "new" }
        format.json { render json: @look.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /looks/1
  # PUT /looks/1.json
  def update
    @look = Look.find(params[:id])

    respond_to do |format|
      if @look.update_attributes(params[:look])
        format.html { redirect_to @look, notice: 'Look was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @look.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /looks/1
  # DELETE /looks/1.json
  def destroy
    @look = Look.find(params[:id])
    @look.destroy

    respond_to do |format|
      format.html { redirect_to looks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/looks_helper.rb
module LooksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ss</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/looks/_form.html.erb
<%= form_for(@look) do |f| %>
  <% if @look.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@look.errors.count, "error") %> prohibited this look from being saved:</h2>

      <ul>
      <% @look.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/looks/edit.html.erb
<h1>Editing look</h1>

<%= render 'form' %>

<%= link_to 'Show', @look %> |
<%= link_to 'Back', looks_path %>

app/views/looks/index.html.erb
<h1>Listing looks</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @looks.each do |look| %>
  <tr>
    <td><%= link_to 'Show', look %></td>
    <td><%= link_to 'Edit', edit_look_path(look) %></td>
    <td><%= link_to 'Destroy', look, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Look', new_look_path %>

app/views/looks/new.html.erb
<h1>New look</h1>

<%= render 'form' %>

<%= link_to 'Back', looks_path %>

app/views/looks/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_look_path(@look) %> |
<%= link_to 'Back', looks_path %>